name: CD - Deploy with Terraform

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 132866222051.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: strapi/strapi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Docker image tag
        run: echo "IMAGE_TAG=${{ github.event.inputs.docker_image_tag }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform -chdir=Terraform-infra init

      - name: Terraform Plan
        run: terraform -chdir=Terraform-infra plan -var="docker_image_tag=$IMAGE_TAG"

      - name: Terraform Apply
        run: terraform -chdir=Terraform-infra apply -auto-approve -var="docker_image_tag=$IMAGE_TAG"
