✅ Terraform workflow

Ye tera jo infrastructure code (provider.tf, network, ec2, alb, etc.) hai usko chalayega.

# .github/workflows/terraform.yml
name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "image_tag=${{ github.event.inputs.image_tag }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_tag=${{ github.event.inputs.image_tag }}"
